
    - name: Update limits
      lineinfile: dest=/etc/security/limits.conf line="{{ item }}" insertbefore='# End of file'
      tags:
      - riak
      - run
      with_items:
      - riak soft nofile 65536
      - riak hard nofile 65536
      sudo: yes

    - name: Get riak dependencies setup script
      get_url: url=https://packagecloud.io/install/repositories/basho/riak/script.deb.sh dest=~/riak-script.deb.sh mode=u+rwx
      tags:
      - riak
      - run
      sudo: yes

    - name: Setup riak dependencies
      command: ~/riak-script.deb.sh
      tags:
      - riak
      - run
      sudo: yes

    - name: Install riak
      apt: pkg=riak
      notify:
      - Update riak configuration
      - Restart riak
      tags:
      - riak
      - run
      sudo: yes
